### ISSUE TITLE
Add columns to Pol table (MB)

### ISSUE THREAD

**Issue by kourosh** [kourosh/tally#30]
The politician table currently only works for members of Congress. Need to modify table to take presidential and congressional candidates. Very likely, the fix is removing a "required" from the model.

* Add column to state which race(s) a politician is running in
* Add a bio text field

**Comment by ikitha** [comment]
I checked the model and there are no validations regarding what we talked about. Can you take a look and let me know what we need to do to proceed?

**Comment by kourosh** [comment]
Huh, you’re right. There is no validation.

I think we still need to make some minor changes. Again, I made the underlying model by scraping some Congress APIs. All we need to do to accommodate presidential candidates is to change some of the column headings. 

Here are the current headings:
title, first name, middlename, last name, fullname, name_suffix, nickname, party, state, district, in_office, gender, phone, fax, website, webform, congress_office, bioguide_id, votesmart_id, fec_id, govtrack_id, crp_id, twitter_id, congresspedia_url, youtube_url, facebook_id, official_rss, senate_class, birthdate, oc_email

Changes:
Add a column called current_office. Add validation to accommodate only these possibilities: House of Reps, Senator, Governor, State Senator, State Rep, Mayor, none.
Delete “in-office”. I think its boolean
Add column “personal_website”
Add column “primary_donation_website” 

That should do the trick for now. 

Can you also update the forms to create a new candidate? I need to create a whole bunch for president.

**Comment by ikitha** [comment]
I already changed the form to what I could. I'll make these changes now :) Also need to figure out superuser validation because i had to turn off devise for that page because it was making me sign up or log in... so devise is working haha

**Comment by ikitha** [comment]
This should be fixed. Let me know if something else needs to be changed.
